Add long help for switch replace command so we have some descripton o…
metal-stack/metalctl pull request #164
Opened 2022-09-08 11:35 UTC by mreiger

…f the replacement process

2022-09-08 12:00 UTC, majst01 submitted a review, later dismissed
OK from my side, one small nit. Maybe @mwennrich and Manfred should review as well

2022-09-08 12:00 UTC, majst01 commented on docs/metalctl_switch.md
> +* [metalctl switch replace](metalctl_switch_replace.md)	 - Put a leaf switch into replace mode in preparation for physical replacement. For a description of the steps involved see the long help.
```suggestion
* [metalctl switch replace](metalctl_switch_replace.md)	 - put a leaf switch into replace mode in preparation for physical replacement. For a description of the steps involved see the long help.
```

2022-09-08 14:33 UTC, mschuller commented
That's a good description of what we did.

2022-09-23 13:11 UTC, Gerrit91 requested changes
There's few parts which should be written in a bit more general manner because deployment is described differently in metal-stack docs. Remember this is an open source project, so it should be aligned to a certain degree. :)

2022-09-23 13:11 UTC, Gerrit91 commented on cmd/switch.go
> +- Replace the switch MAC address in the metal-deployment
```suggestion
- Replace the switch MAC address in the metal-stack deployment configuration
```

2022-09-23 13:11 UTC, Gerrit91 commented on cmd/switch.go
> +- Make sure that interfaces on the new switch do not get connected to the PXE-bridge immediately by setting the interfaces dictionary of the respective leaf switch to [] in the metal-deployment repos
```suggestion
- Make sure that interfaces on the new switch do not get connected to the PXE-bridge immediately by setting the interfaces list of the respective leaf switch to [] in the metal-stack deployment configuration
```

2022-09-23 13:11 UTC, Gerrit91 commented on cmd/switch.go
> +- Deploy metal-core on the switch with the "deploy <partition>" CI job
```suggestion
- Deploy the switch plane and metal-core through metal-stack deployment CI job
```

2023-01-19 13:32 UTC, merged